import 'server-only';

import { type NextRequest, NextResponse } from 'next/server';

import { dbAdmin } from '@/lib/db/client';
import { metaDeletionRequests } from '@/lib/db/schema';
import { env } from '@/lib/env';
import { log } from '@/lib/log';
import { validateSignedRequest } from '@/lib/meta/signed-request';

/**
 * Meta App Review — Data Deletion Callback.
 *
 * Meta validates this endpoint without credentials (no Authorization
 * header, no cookie) → it MUST be in `PUBLIC_PATHS` (see proxy.ts).
 * Same pattern as `/api/health` (commit 05a2afe).
 *
 * Contract:
 *   POST body:     application/x-www-form-urlencoded
 *                  signed_request=<base64url-sig>.<base64url-payload>
 *   Response 200:  { url, confirmation_code }
 *   Response 400:  malformed body or signature failed
 *   Response 503:  server misconfigured (META_APP_SECRET missing)
 *
 * Meta polls the `url` page periodically to display the user's
 * deletion status. The actual purge of the user's data happens
 * asynchronously — a future cron (TBD C50) walks
 * `meta_deletion_requests WHERE status = 'pending'` and processes
 * each one. This route only ACKs + persists.
 *
 * Latency budget per Meta spec: < 5s. We do one DB insert via
 * service_role (no per-tenant context — system table) and return.
 */
export const dynamic = 'force-dynamic';

const STATUS_PAGE_URL =
  'https://blacknel.com/es/privacy#data-deletion-status';

export async function POST(request: NextRequest): Promise<NextResponse> {
  if (!env.META_APP_SECRET) {
    log.error('meta.data_deletion.misconfigured — META_APP_SECRET not set');
    return NextResponse.json(
      { error: 'server_misconfigured' },
      { status: 503 },
    );
  }

  // Meta posts form-urlencoded. Be defensive: also accept JSON body in
  // case someone manually probes (returns 400, still doesn't crash).
  let signedRequest: string | null = null;
  const contentType = request.headers.get('content-type') ?? '';
  try {
    if (contentType.includes('application/x-www-form-urlencoded')) {
      const form = await request.formData();
      const v = form.get('signed_request');
      signedRequest = typeof v === 'string' ? v : null;
    } else if (contentType.includes('application/json')) {
      const body = (await request.json()) as { signed_request?: unknown };
      signedRequest =
        typeof body.signed_request === 'string' ? body.signed_request : null;
    } else {
      // Last-ditch: try formData anyway. Meta is the only legitimate caller.
      const form = await request.formData();
      const v = form.get('signed_request');
      signedRequest = typeof v === 'string' ? v : null;
    }
  } catch (err) {
    log.warn({ err }, 'meta.data_deletion.body_parse_failed');
    return NextResponse.json({ error: 'invalid_body' }, { status: 400 });
  }

  if (!signedRequest) {
    return NextResponse.json(
      { error: 'missing_signed_request' },
      { status: 400 },
    );
  }

  const payload = validateSignedRequest(signedRequest, env.META_APP_SECRET);
  if (!payload) {
    log.warn('meta.data_deletion.signature_invalid');
    return NextResponse.json(
      { error: 'invalid_signed_request' },
      { status: 400 },
    );
  }

  // Persist a `pending` row. `confirmation_code` is generated by the DB
  // (defaultRandom()) and returned via RETURNING.
  let row: { confirmationCode: string } | undefined;
  try {
    const inserted = await dbAdmin(async (tx) =>
      tx
        .insert(metaDeletionRequests)
        .values({
          metaUserId: payload.user_id,
          signedRequest,
        })
        .returning({ confirmationCode: metaDeletionRequests.confirmationCode }),
    );
    row = inserted[0];
  } catch (err) {
    log.error({ err }, 'meta.data_deletion.persist_failed');
    return NextResponse.json({ error: 'persist_failed' }, { status: 500 });
  }

  if (!row) {
    return NextResponse.json({ error: 'persist_failed' }, { status: 500 });
  }

  log.info(
    { confirmationCode: row.confirmationCode, metaUserId: payload.user_id },
    'meta.data_deletion.accepted',
  );

  return NextResponse.json(
    {
      url: `${STATUS_PAGE_URL}?code=${row.confirmationCode}`,
      confirmation_code: row.confirmationCode,
    },
    { status: 200 },
  );
}
