import 'server-only';

import { and, eq } from 'drizzle-orm';

import { type AnyPgTx } from '../../db/client';
import { inboxMessages, inboxThreads } from '../../db/schema';
import { AppError } from '../../errors';

/**
 * Dispatches an approved `inbox_reply` approval into the inbox.
 *
 * Runs INSIDE the same transaction as the approval status update. If
 * the insert raises (FK miss, RLS bounce, anything) the outer txn
 * rolls back and the approval remains pending — `approveAction` never
 * observes a partial state.
 *
 * The `approval.entityId` UUID was pre-generated by `send-reply.ts`
 * at the moment the approval was created; we reuse it as the
 * `inbox_messages.id` so the audit trail (`audit_events.entity_id`)
 * stays consistent across the routed→approved transition.
 */

interface InboxReplyPayload {
  kind: 'inbox_reply';
  threadId: string;
  messageBody: string;
  language?: string;
  savedReplyId?: string | null;
  aiGenerated?: boolean;
}

export interface InboxApprovalRow {
  id: string;
  organizationId: string;
  entityId: string;
  proposedPayload: unknown;
}

function isInboxReplyPayload(value: unknown): value is InboxReplyPayload {
  if (!value || typeof value !== 'object') return false;
  const v = value as Record<string, unknown>;
  return (
    v.kind === 'inbox_reply' &&
    typeof v.threadId === 'string' &&
    typeof v.messageBody === 'string'
  );
}

export async function dispatchInboxReplyApproval(
  tx: AnyPgTx,
  approval: InboxApprovalRow,
  actorUserId: string,
): Promise<{ messageId: string }> {
  if (!isInboxReplyPayload(approval.proposedPayload)) {
    throw new AppError(
      'VALIDATION_ERROR',
      `Approval ${approval.id} proposed_payload is not a valid inbox_reply shape.`,
      { meta: { approvalId: approval.id } },
    );
  }
  const payload = approval.proposedPayload;

  // Confirm the thread still belongs to the same org (defense in depth —
  // RLS WITH CHECK on the insert would also reject, but failing here
  // first gives us a clearer audit message).
  const threadRows = await tx
    .select({ id: inboxThreads.id })
    .from(inboxThreads)
    .where(
      and(
        eq(inboxThreads.id, payload.threadId),
        eq(inboxThreads.organizationId, approval.organizationId),
      ),
    )
    .limit(1);
  if (threadRows.length === 0) {
    throw new AppError(
      'NOT_FOUND',
      'Thread referenced by this approval no longer exists.',
      { meta: { approvalId: approval.id, threadId: payload.threadId } },
    );
  }

  // Use the pre-generated UUID so the message id matches the audit
  // trail laid down when the approval was created.
  await tx.insert(inboxMessages).values({
    id: approval.entityId,
    organizationId: approval.organizationId,
    threadId: payload.threadId,
    direction: 'outbound',
    authorType: payload.aiGenerated ? 'ai' : 'user',
    authorId: actorUserId,
    body: payload.messageBody,
    sentAt: new Date(),
  });

  // Bump thread `last_message_at` so the conversation jumps to the
  // top of the inbox list.
  await tx
    .update(inboxThreads)
    .set({ lastMessageAt: new Date() })
    .where(
      and(
        eq(inboxThreads.id, payload.threadId),
        eq(inboxThreads.organizationId, approval.organizationId),
      ),
    );

  return { messageId: approval.entityId };
}
